### ISSUE TITLE
PST file(s)  shrinking after executing the script

### ISSUE THREAD

**Issue by yuessir** [teamoto/vba-o365-upload-pst#1]
After executing the  script, the original local .pst file(s) be shrunk?
Is that normal behaviors?

**Comment by teamoto** [comment]
It can be because what this script does is to move every single mail item to a target online arching.
This means that once a mail item is moved, the mail item is gone from the original pst.
Unless doing it, I could not resume the migration job when an error happened and migration stopped in the middle.
